### PR TITLE
Project to validate fields of the contact us form

### PR DESCRIPTION
**Pull request by siddghosh108**
This is the project where the different fields of the contact us form section iare validated

### CODE REVIEW

**Review by AmaduKamara — COMMENTED** [review]
# Status: Invalid Submission ❌ ❌ ❌

Hi @siddghosh108,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that your partner did not make a contribution to.

- [x] Kindly have a contribution made by your partner/s as this project is a pair programming project. So far, it's only you that made a commit to this branch, but it's required you and your partners make a contribution, except otherwise, you have proof that student success allowed you to work solo on this project 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Comment by mrgold10** [comment]
Hi @AmaduKamara,

Marco here from the Student Success team. Please proceed with reviewing this PR, since @siddghosh108 partner has taken a leave of absence, we are allowing them to proceed solo for the remainder of this week.

If you have any doubts, please send me a Slack DM in the Code-Reviewers workspace

**Comment by AmaduKamara** [comment]
Ok, great, thank you.

Kindly resubmit for a review. Another reviewer will proceed with the
review.

**Comment by AmaduKamara** [comment]
Okay, that's great. Thank you.

Kindly, the student should resubmit for a review. Another reviewer will proceed with the review.

**Comment by AmaduKamara** [comment]
## Hi @siddghosh108,

Kindly add the HTML, CSS, and JavaScript Linter config for your project so Linter checks are passed. 

For the previous issue, don't worry about that, once Linter is set up in your project, another code reviewer will review your work.

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @siddghosh108,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

giphy (1)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
